replicaCount: 2
image:
  repository: us-central1-docker.pkg.dev/devops-project-489401/bookstore/order-service
  tag: 626f8c635135bc4abf3dfd98fa8afa14e068a468
port: 3001
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
