replicaCount: 2
image:
  repository: us-central1-docker.pkg.dev/devops-project-489401/bookstore/frontend
  tag: 626f8c635135bc4abf3dfd98fa8afa14e068a468
port: 80
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
