replicaCount: 2
image:
  repository: us-central1-docker.pkg.dev/devops-project-489401/bookstore/frontend
  tag: cddc24d3e5fef77f6bd669c5b6ada4d59c437859
port: 80
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
